// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASww7TVV1yb_gMkpNRmTF0AQuN9Jo21Dk',
    appId: '1:767742131819:android:d4745038ee114d393abb2e',
    messagingSenderId: '767742131819',
    projectId: 'outfit4rent-c7575',
    databaseURL: 'https://outfit4rent-c7575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'outfit4rent-c7575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKTbw34J5Ukb256QcdeyGxTZoK1TcGtU',
    appId: '1:767742131819:ios:d9d5e82b3ab6b3b53abb2e',
    messagingSenderId: '767742131819',
    projectId: 'outfit4rent-c7575',
    databaseURL: 'https://outfit4rent-c7575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'outfit4rent-c7575.appspot.com',
    iosClientId: '767742131819-nd5kk6e6cppn1rp8jr4qci16ni3vqd9v.apps.googleusercontent.com',
    iosBundleId: 'com.outfit4rent.app',
  );
}
