# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
  # Runs this action when you push on master
  push:
    branches: ["main"]
  # Runs this when a PR against master is created
  pull_request:
    branches: ["main"]

jobs:
  flutter_job:
    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest

    steps:
      # Clones the project on the machine
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          check-latest: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --fatal-warnings

      - name: Build Android APK
        run: flutter build apk

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip iOS output
        run: zip -qq -r -9 outfit4rent.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload apk to Firebase distribution
      # - name: Upload apk to Firebase distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      #     serviceCredentialsFileContent: ${{ secrets.SERVICE_CREDENTIALS_FILE_CONTENT }}
      #     groups: outfit4rent
      #     file: build/app/outputs/apk/release/outfit4rent-release.apk

      # Upload ipa to Firebase distribution
      # - name: Upload ipa to Firebase distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
      #     serviceCredentialsFileContent: ${{ secrets.SERVICE_CREDENTIALS_FILE_CONTENT }}
      #     groups: outfit4rent
      #     file: build/ios/iphoneos/outfit4rent.ipa

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/outfit4rent.ipa"
          tag: v1.0.2
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
