# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
  # Runs this action when you push on master
  push:
    branches: ["main"]
  # Runs this when a PR against master is created
  pull_request:
    branches: ["main"]

jobs:
  flutter_job:
    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest

    steps:
      # Clones the project on the machine
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # # Verifies if the dart code is formatted well
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   # --set-exit-if-changed stops execution if the any code is not well formatted
      #   # --output=none prints files which needs to be formatted
      # Checks for Symantic errors. Can be configured using analysis_options.yaml

      - name: Analyze project source
        run: flutter analyze --fatal-warnings

      - name: Build Android APK
        run: flutter build apk

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip iOS output
        run: zip -qq -r -9 outfit4rent.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload apk to Firebase distribution
      # - name: Upload apk to Firebase distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      #     serviceCredentialsFileContent: ${{ secrets.SERVICE_CREDENTIALS_FILE_CONTENT }}
      #     groups: outfit4rent
      #     file: build/app/outputs/flutter-apk/app-release.apk
      # build/app/outputs/apk/release/outfit4rent-release.apk

      - name: List APK directory
        run: ls -l build/app/outputs/apk/release

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/outfit4rent.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      # - name: Push IOS to Releases
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     file: |
      #       build/app/outputs/apk/release/outfit4rent.apk
      #       build/ios/iphoneos/outfit4rent.ipa
      #     tag: ${{ github.ref }}
      #     repo_token: ${{ secrets.TOKEN }}
      #     release_name: v1.0.${{ github.run_number }}
      #     prerelease: true
      #     overwrite: true
